import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  AGENT_RUN_COST_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_CURRENT_ACTION_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_ENDED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_EXTERNAL_ID_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_HEARTBEAT_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_INPUT_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_OBJECT_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_OUTPUT_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_PROGRESS_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_STARTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  AGENT_RUN_TOKENS_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export const AGENT_RUN_STATUS_OPTIONS = [
  {
    id: '60911f3b-ae7d-467f-a50c-a21932bf34cc',
    value: 'QUEUED',
    label: 'Queued',
    position: 0,
    color: 'gray',
  },
  {
    id: 'fa3ca90d-f3ba-49e9-818d-b82fab063e49',
    value: 'RUNNING',
    label: 'Running',
    position: 1,
    color: 'green',
  },
  {
    id: 'c370156d-2dd8-4414-83cc-2448ef94fd37',
    value: 'WAITING',
    label: 'Waiting',
    position: 2,
    color: 'blue',
  },
  {
    id: 'f7172cbc-16c8-47ff-b4a6-676ff0740d32',
    value: 'BLOCKED',
    label: 'Blocked',
    position: 3,
    color: 'orange',
  },
  {
    id: '893743f6-25c5-431d-a05d-d1bad1a0bc6a',
    value: 'COMPLETED',
    label: 'Completed',
    position: 4,
    color: 'green',
  },
  {
    id: 'a524f56b-c1fc-41ef-83d0-33832904254f',
    value: 'FAILED',
    label: 'Failed',
    position: 5,
    color: 'red',
  },
  {
    id: 'aa3d4ad6-0fd9-4454-a333-e17246e3e7a0',
    value: 'CANCELLED',
    label: 'Cancelled',
    position: 6,
    color: 'gray',
  },
] as const;

export default defineObject({
  universalIdentifier: AGENT_RUN_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'agentRun',
  namePlural: 'agentRuns',
  labelSingular: 'Agent run',
  labelPlural: 'Agent runs',
  description: 'One execution instance of an agent.',
  icon: 'IconPlayerPlay',
  labelIdentifierFieldMetadataUniversalIdentifier:
    AGENT_RUN_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: AGENT_RUN_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: AGENT_RUN_EXTERNAL_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'externalId',
      label: 'Run ID',
      icon: 'IconHash',
      isUnique: true,
    },
    {
      universalIdentifier: AGENT_RUN_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconActivity',
      defaultValue: "'QUEUED'",
      options: [...AGENT_RUN_STATUS_OPTIONS],
    },
    {
      universalIdentifier: AGENT_RUN_STARTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'startedAt',
      label: 'Started at',
      icon: 'IconClockPlay',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_ENDED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'endedAt',
      label: 'Ended at',
      icon: 'IconClockCheck',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_HEARTBEAT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'lastHeartbeatAt',
      label: 'Last heartbeat',
      icon: 'IconHeartbeat',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_PROGRESS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'progress',
      label: 'Progress (%)',
      icon: 'IconPercentage',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_CURRENT_ACTION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'currentAction',
      label: 'Current action',
      icon: 'IconPlayerTrackNext',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_INPUT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RAW_JSON,
      name: 'input',
      label: 'Input',
      icon: 'IconBraces',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_OUTPUT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'output',
      label: 'Output',
      icon: 'IconSparkles',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'error',
      label: 'Error',
      icon: 'IconAlertTriangle',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_COST_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'costUsd',
      label: 'Cost (USD)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: AGENT_RUN_TOKENS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'tokens',
      label: 'Tokens',
      icon: 'IconSum',
      isNullable: true,
    },
  ],
});
